apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3 #three replicas of the multiclient pod
  selector:
    matchLabels:
      component: web #the component of our app, that the Deployment object is going to be mention is the
                      #web or frontend... the Deployment is going to identify a specific pod 
                      #by refering this selector
  template: #refers to the configuration of the pods
    metadata:
      labels:
        component: web #this label will identify this particular pod.
    spec:
      containers: #now specifying all the different containers that are going to run inside this pod.
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000 #port mapped to this multi-client image
            





